image: registry.secoder.net/tool/deployer

stages:
  - pre
  - build
  - test
  - deploy

build_cache:
  image: node:14
  stage: pre
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - yarn.lock
  script:
    - yarn config set registry https://mirrors.cloud.tencent.com/npm/
    - yarn install

build:
  stage: build
  needs: [build_cache]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - yarn.lock
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build

style-test:
  stage: test
  needs: [build_cache]
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - yarn.lock
  script:
    - yarn lint

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master

deploy-dev:
  stage: deploy
  script:
    - deployer dyno replace frontend-dev "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  allow_failure: true
  only:
    - dev
